# Generated by Django 5.2.8 on 2025-12-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlgorithmComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название алгоритма', max_length=50, verbose_name='Алгоритм')),
                ('security', models.PositiveIntegerField(help_text='Введите уровень безопасности', verbose_name='Уровень безопасности')),
                ('speed', models.PositiveIntegerField(help_text='Введите скорость работы', verbose_name='Скорость')),
                ('key_size', models.PositiveIntegerField(help_text='Введите размер ключа', verbose_name='Размер ключа')),
                ('type', models.CharField(help_text='Введите тип', max_length=50, verbose_name='Тип')),
                ('year', models.IntegerField(help_text='Введите год создания', verbose_name='Год создания')),
                ('explanation', models.TextField(help_text='Введите текст определения', verbose_name='Определение')),
                ('use_case', models.TextField(help_text='Введите способы применения', verbose_name='Применение')),
            ],
            options={
                'verbose_name': 'Алгоритм для сравнения',
                'verbose_name_plural': 'Алгоритмы для сравнения',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['name'], name='security_al_name_c3f451_idx')],
            },
        ),
    ]
