# Generated by Django 5.2.8 on 2025-12-02 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Уникальный идентификатор категории (symmetric, asymmetric, hash, modern и т.д.)', unique=True, verbose_name='Ключ категории')),
                ('title', models.CharField(help_text='Название категории', max_length=150, verbose_name='Заголовок')),
                ('description', models.TextField(help_text='Краткое описание категории', verbose_name='Описание')),
                ('icon', models.CharField(help_text='Ключ иконки (например: key, key-round, hash, cpu)', max_length=50, verbose_name='Иконка')),
                ('color', models.CharField(help_text='Классы Tailwind для градиента (например: from-blue-500 to-blue-600)', max_length=50, verbose_name='Цветовой градиент')),
            ],
            options={
                'verbose_name': 'Категория криптографии',
                'verbose_name_plural': 'Категории криптографии',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserOperationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('encrypt', 'Encrypt'), ('decrypt', 'Decrypt'), ('sign', 'Sign'), ('verify', 'Verify')], max_length=20, verbose_name='Тип операции')),
                ('algorithm', models.CharField(help_text='Название или код алгоритма, использованного в операции', max_length=100, verbose_name='Алгоритм')),
                ('input_data', models.TextField(help_text='Входные данные операции (может быть обрезано на клиенте)', verbose_name='Входные данные')),
                ('output_data', models.TextField(help_text='Результат операции (может быть обрезано на клиенте)', verbose_name='Результат')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время операции')),
            ],
            options={
                'verbose_name': 'История операций пользователя',
                'verbose_name_plural': 'История операций пользователей',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WebImplementationExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Уникальный идентификатор примера (например: jwt, aes, oauth)', unique=True, verbose_name='Ключ примера')),
                ('title', models.CharField(help_text='Краткое название примера', max_length=150, verbose_name='Заголовок')),
                ('description', models.TextField(help_text='Краткое текстовое описание примера', verbose_name='Описание')),
                ('code', models.TextField(help_text='Фрагмент кода, который будет показан на фронтенде', verbose_name='Код примера')),
            ],
            options={
                'verbose_name': 'Веб-пример реализации криптографии',
                'verbose_name_plural': 'Веб-примеры реализации криптографии',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AlgorithmComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название алгоритма', max_length=50, verbose_name='Алгоритм')),
                ('security', models.PositiveIntegerField(help_text='Введите уровень безопасности', verbose_name='Уровень безопасности')),
                ('speed', models.PositiveIntegerField(help_text='Введите скорость работы', verbose_name='Скорость')),
                ('key_size', models.PositiveIntegerField(help_text='Введите размер ключа', verbose_name='Размер ключа')),
                ('type', models.CharField(help_text='Введите тип', max_length=50, verbose_name='Тип')),
                ('year', models.IntegerField(help_text='Введите год создания', verbose_name='Год создания')),
                ('explanation', models.TextField(help_text='Введите текст определения', verbose_name='Определение')),
                ('use_case', models.TextField(help_text='Введите способы применения', verbose_name='Применение')),
            ],
            options={
                'verbose_name': 'Алгоритм для сравнения',
                'verbose_name_plural': 'Алгоритмы для сравнения',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['name'], name='security_al_name_c3f451_idx')],
            },
        ),
        migrations.CreateModel(
            name='CryptoAlgorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название алгоритма')),
                ('key_size', models.CharField(blank=True, help_text='Например: 128, 192, 256 бит', max_length=100, verbose_name='Размер ключа')),
                ('security', models.CharField(blank=True, help_text='Например: Очень высокая, Высокая, Средняя, Низкая', max_length=100, verbose_name='Уровень безопасности')),
                ('speed', models.CharField(blank=True, help_text='Например: Высокая, Средняя, Низкая', max_length=100, verbose_name='Скорость')),
                ('description', models.TextField(help_text='Общее описание алгоритма', verbose_name='Описание')),
                ('technical_details', models.TextField(blank=True, help_text='Более техническое описание (опционально)', verbose_name='Технические детали')),
                ('vulnerabilities', models.TextField(blank=True, help_text='Известные уязвимости (опционально)', verbose_name='Уязвимости')),
                ('simple_explanation', models.TextField(blank=True, help_text='Объяснение простыми словами (опционально)', verbose_name='Простое объяснение')),
                ('real_world_example', models.TextField(blank=True, help_text='Где используется алгоритм (опционально)', verbose_name='Примеры из реального мира')),
                ('applications', models.JSONField(blank=True, default=list, help_text='Список применений алгоритма', verbose_name='Применение')),
                ('advantages', models.JSONField(blank=True, default=list, help_text='Список преимуществ алгоритма', verbose_name='Преимущества')),
                ('disadvantages', models.JSONField(blank=True, default=list, help_text='Список недостатков алгоритма', verbose_name='Недостатки')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='algorithms', to='security.cryptocategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Криптоалгоритм',
                'verbose_name_plural': 'Криптоалгоритмы',
                'ordering': ['id'],
            },
        ),
    ]
