# Generated by Django 5.2.8 on 2025-12-01 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOperationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('encrypt', 'Encrypt'), ('decrypt', 'Decrypt'), ('sign', 'Sign'), ('verify', 'Verify')], max_length=20, verbose_name='Тип операции')),
                ('algorithm', models.CharField(help_text='Название или код алгоритма, использованного в операции', max_length=100, verbose_name='Алгоритм')),
                ('input_data', models.TextField(help_text='Входные данные операции (может быть обрезано на клиенте)', verbose_name='Входные данные')),
                ('output_data', models.TextField(help_text='Результат операции (может быть обрезано на клиенте)', verbose_name='Результат')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время операции')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_history', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История операций пользователя',
                'verbose_name_plural': 'История операций пользователей',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='security_us_user_id_3a95ec_idx'), models.Index(fields=['operation_type'], name='security_us_operati_f2433b_idx')],
            },
        ),
    ]
