# Generated by Django 5.2.8 on 2025-12-02 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('security', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='useroperationhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_history', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='useroperationhistory',
            index=models.Index(fields=['user', 'timestamp'], name='security_us_user_id_3a95ec_idx'),
        ),
        migrations.AddIndex(
            model_name='useroperationhistory',
            index=models.Index(fields=['operation_type'], name='security_us_operati_f2433b_idx'),
        ),
    ]
