from .web_implementation_example_admin import WebImplementationExampleAdmin
from .algorithm_comparison_admin import AlgorithmComparisonAdmin
from .crypto_category_admin import CryptoCategoryAdmin
from .crypto_algorithm_admin import CryptoAlgorithmAdmin
